### ISSUE TITLE
About Test Label

### ISSUE THREAD

**Issue by lamaMajedd** [PatrickTUM/multimodalCD_ISPRS21#3]
Thanks for sharing this code
I would ask you about Test Labels if it is available or not?

**Comment by PatrickTUM** [comment]
Hello @lamaMajedd,

you are welcome! For the original Sentinel-2 observations and pixel-wise annotations, they are available [here](https://ieee-dataport.org/open-access/oscd-onera-satellite-change-detection). Hoping this helps!
