### ISSUE TITLE
Could you upload the relevant files

### ISSUE THREAD

**Issue by Jason-Study** [PatrickTUM/multimodalCD_ISPRS21#4]
Dear @PatrickTUM,
First of all, thank you for the nice repo and data.

I am a freshman and I am trying to run this code, but there seems lack of the files named `SiamUnet_diff_multi` and `FresUNet_multi` in the file of `test.py`(Lines 414 and 415). Could you provide me the relevant files or methods to find these files?

```
elif TYPE == 4:
        if NET == 'Unet': net, net_name = Unet(2*13+2*2, 2), 'FC-EF-multi' # same architecture as the other network
        if NET == 'SiamUnet_conc-simple': net, net_name = SiamUnet_conc(13+2, 2), 'FC-Siam-conc-simple'
        if NET == 'SiamUnet_conc': net, net_name = SiamUnet_conc_multi((13, 2), 2), 'FC-Siam-conc-complex'
        if NET == 'SiamUnet_diff': net, net_name = SiamUnet_diff_multi(13, 2, 2), 'FC-Siam-diff'
        if NET == 'FresUNet': net, net_name = FresUNet_multi(2 * 13 + 2*13, 2), 'FresUNet'
```

Thank you very much!

**Comment by PatrickTUM** [comment]
Dear Jason,

you are welcome and my apologies for the confusion about these two models. The "SiamUnet_diff_multi" and "FresUNet_multi" do not exist yet and hence are not contained neither in the publication or in the code.

Hence they are more of a placeholder right now, in doing so we wanted to keep the structure of the [original](https://github.com/rcdaudt/fully_convolutional_change_detection/blob/master/fully-convolutional-change-detection.ipynb) code base.

I'd propose you to use the other models instead, which are implemented. If you may implement"SiamUnet_diff_multi" or "FresUNet_multi" in the future (this could be an interesting research idea) then I'd be happy to accept your pull request.

So long, my apologies for the confusion and that the two models aren't implemented yet.
Hoping this helps!

**Comment by Jason-Study** [comment]
Okay. Thanks for your help! :)
